### ISSUE TITLE
[EE] No machine type on new pipeline

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreio/semaphore#187]
### Describe the bug

Creating a new pipeline in Workflow builder results in the empty `machine type` parameter, in turn making the pipeline invalid. 

As an alternative solution, on the self-hosted versions of Semaphore, when new pipeline is created the machine type should be set to the first available machine, and environment to Docker fixed values. 

So it would look something like:

```yaml
agent:
  machine:
    type: <FIRST AGENT IN THE LIST>
    os_image: ''
  containers:
    - name: main
      image: 'semaphoreci/ubuntu:20.04'
```

### Steps to reproduce

1. Open the **EE** version of Semaphore
2. In existing project, open the workflow editor
3. Click on "+ Add Promotion" button to create a new pipeline
4. Run the workflow
5. Observe the error
6. Check the promotion pipeline yaml file

### Additional context

⚠️ This happens only on the EE version
