### ISSUE TITLE
Promotion Dependencies

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreio/semaphore#368]
### Is your improvement proposal related to a problem? Please describe.

Currently, users cannot make a promotion dependent on the successful completion of multiple other promotions within the same workflow. This limitation prevents users from modeling complex deployment workflows where certain stages should only run after multiple parallel promotions have succeeded. 

Specific pain points users encounter:
- Cannot block a promotion until multiple other promotions complete (e.g., "Publish hashrelease" should wait for all "Publish images" promotions)
- No way to ensure manual promotions are only enabled after specific blocks or promotions complete
- Cannot model fan-in patterns where multiple parallel promotions converge before proceeding to the next stage
- Promotions lack description fields to communicate dependencies in the UI
- Users need to rely on workarounds like checking previous block results within the promoted pipeline itself

### Describe the solution you'd like

Enable promotions to have dependencies on other promotions, similar to how blocks can depend on multiple blocks:

1. **Add promotion dependencies**: Allow specifying which promotions must complete successfully before a promotion becomes available
   ```yaml
   promotions:
     - name: "Deploy to us-west-2 nonprod"
       pipeline_file: deploy-regional.yml
       parameters:
         env_vars:
           - name: REGION
             default_value: us-west-2
           - name: ENVIRONMENT
             default_value: nonprod
       dependencies: []
       
     - name: "Deploy to us-east-1 nonprod"
       pipeline_file: deploy-regional.yml
       parameters:
         env_vars:
           - name: REGION
             default_value: us-east-1
           - name: ENVIRONMENT
             default_value: nonprod
       dependencies: []
       
     - name: "Deploy global resources to prod"
       pipeline_file: deploy-global-prod.yml
       dependencies:
         - deploy-regional.yml  # All instances of deploy-regional.yml must complete, regardless of their parameters
   ```

2. **Fan-in support**: Enable modeling of convergence patterns where multiple parallel promotions must all succeed before the next stage can begin. For example:
   - Build artifacts → triggers multiple parallel regional deployments (same pipeline file with different parameters)
   - All regional deployments must complete → before global production deployment can proceed
   - This creates a "fan-out" (one-to-many) followed by "fan-in" (many-to-one) pattern
   - The dependency system should recognize all promotions using the same pipeline file, even with different parameters

3. **Visual indicators in UI**: Show promotion dependencies clearly, with disabled state for promotions waiting on dependencies. Display which dependencies are pending vs completed.

4. **Support for both manual and auto-promotions**: Dependencies should work for both promotion types, enabling/triggering them only after all specified pipeline files have been successfully promoted and completed in the current workflow.

5. **Add description field to promotions**: Allow users to document promotion purposes and dependencies directly in the YAML and visible in the UI
