### ISSUE TITLE
Webhook notifications for tags

### ISSUE THREAD

**Issue by AleksandarCole** [semaphoreio/semaphore#369]
### Is your improvement proposal related to a problem? Please describe.

Users are trying to set up webhook notifications specifically for failed tag builds, but these notifications are not triggering as expected. Currently, webhook notifications in the YAML configuration don't support tag-based filtering, making it impossible to create notifications that trigger exclusively for tag builds. This is particularly problematic for users who use tags for production releases and need immediate alerts when tag builds fail.

### Describe the solution you'd like

Add support for tag-based filtering in the YAML notification configuration:

```yaml
notifications:
  - name: "Production Release Failures"
    type: webhook
    endpoint: "https://example.com/webhook"
    events:
      - pipeline_done
    filter:
      result: failed
      tag: "v*"  # New: filter by tag pattern
      
  - name: "Tag Build Notifications"
    type: webhook  
    endpoint: "https://example.com/webhook"
    events:
      - pipeline_done
    filter:
      result: failed
      ref_type: tag  # New: filter by reference type (tag vs branch)
      tag: "release-*"  # New: tag pattern matching
```

Key features needed:
- `ref_type` field to distinguish between tag and branch builds
- `tag` field for pattern matching on tag names
- Ability to exclude branch builds when only tag notifications are desired
- Support for wildcards and regex patterns in tag matching
